#!/usr/bin/python
import sys
def collapse(s):
    si = 0
    while si < len(s) - 1:
        if abs(ord(s[si]) - ord(s[si+1])) == 32:
            del s[si]
            del s[si]
            si -= 1 if si > 0 else 0
        else:
            si += 1
    return s
data = collapse(list(open(sys.argv[1], 'r').read().strip()))
print "{} units".format(len(data))
